### ISSUE TITLE
Please enter api key to get started.

### ISSUE THREAD

**Issue by jbrunno** [dmamills/radio#17]
I installed on my machine and this message appears when I try to access / admin
Please enter api key to get started.
where do I get this Api Key
can you help me???

**Comment by dmamills** [comment]
Hello!

The API key can be found in your `.env` file for the server [here](https://github.com/dmamills/opensourceradio/blob/master/server/.env.example):

`RTMP_HTTP_PASS=verycoolcat`

It's obviously recommended that you change it from the default!
Let me know if that solves your problem :)
